# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Gauss-Seidel iterative method using Rcpp
#' @description Gauss-Seidel iterative method using Rcpp
#' @param A Matrix of coefficients.
#' @param b The right-hand side of a linear system. 
#' @param x0 Iterate the initial value. 
#' @param N Number of iterations.
#' @return Results of iterative solutions for linear systems.
#' @examples
#' \dontrun{
#' set.seed(1)
#' n <- 1e3
#' A <- sample(0:1,n^2,replace = TRUE,prob=c(0.95,0.05))
#' dim(A) <- c(n,n)
#' A <- -A + diag(rowSums(A)+1)
#' M_x <- rnorm(n)
#' b <- A %*% M_x
#' x0 <- array(rep(0,n))
#' x <- Gauss_Seidel(A,b,x0,1e3)
#' }
#' @export
Gauss_Seidel <- function(A, b, x0, N = 10L) {
    .Call('_StatComp22074_Gauss_Seidel', PACKAGE = 'StatComp22074', A, b, x0, N)
}

#' @title Gibbs sampling of bivariate normal variables using Rcpp
#' @description Gibbs sampling of bivariate normal variables using Rcpp
#' @param x0 Initial sampling value of x. 
#' @param y0 Initial sampling value of y. 
#' @param N Number of samples.
#' @return Sample results for binary variables.
RandomC <- function(x0, y0, N) {
    .Call('_StatComp22074_RandomC', PACKAGE = 'StatComp22074', x0, y0, N)
}

